### ISSUE TITLE
Unproved checks with FSF build

### ISSUE THREAD

**Issue by simonjwright** [rod-chapman/SPARKNaCl#16]
This is really just for info.

I’ve built branch fsf against GCC 12.0.1 of 20220204 ([discussion](https://forward-in-code.blogspot.com/2022/02/spark2014-and-fsf-gcc.html), [compiler](https://github.com/simonjwright/distributing-gcc/releases/tag/gcc-12.0.1), [spark2014](https://github.com/simonjwright/spark2014/releases/tag/macos-0.1)).

The prover versions are
* alt-ergo: 2.4.1
* cvc4: 1.8
* z3: 4.8.12

Running SPARKNaCl fca8934 of 16 December (latest) against this, I get 6 unproved checks:

```
sparknacl.adb:114:10: medium: assertion might fail
  114>|        ((for all K in Index_31 range 0 .. 15 =>
  ... | ...
  117 |            T (K) = 0));

sparknacl.adb:161:16: medium: loop invariant might fail in first iteration, cannot prove T (K) <= (I64 (I + 1) * MGFLP)
  161 |               T (K) <= (I64 (I + 1) * MGFLP));
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

sparknacl-sign.adb:479:54: medium: range check might fail
  479 |                  Adjustment := (L16 (J - (I - 32))) * XLI;
      |                                ~~~~~~~~~~~~~~~~~~~~~^~~~~
  reason for check: result of multiplication must fit in the target type of the assignment
  possible fix: loop invariant at line 572 should mention XLI
  572 |            pragma Loop_Invariant
      |            ^ here

sparknacl-sign.adb:481:28: medium: range check might fail
  481 |                  Carry := ASR_8 (XLJ + 128);
      |                           ^~~~~~~~~~~~~~~~
  reason for check: value must fit in the target type of the assignment

sparknacl-sign.adb:496:21: medium: loop invariant might fail in first iteration, cannot prove XL (K) in PRL
  496 |                    XL (K) in PRL);
      |                    ^~~~~~~~~~~~~

sparknacl-sign.adb:667:18: medium: loop invariant might not be preserved by an arbitrary iteration, cannot prove XL (K) in Step2_XL_Limb
  667 |                 XL (K) in Step2_XL_Limb);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rod-chapman** [comment]
Thanks for reporting that. It is indeed annoying that the more recent provers do not guarantee no regressions.
It might be possible to change the step-limit and/or timeout flags for them to see if that helps, but this is very much a trial-and-error process which I don't recommend...

**Comment by rod-chapman** [comment]
I will try to persuade AdaCore to let me have a wavefront of SPARK Pro and/or the Community 2022 edition as and when it becomes available to see if that regresses too...

**Comment by rod-chapman** [comment]
Overtaken by events now with the release of GCC 12.1.0 and the adoption of CVC5. Closing this for now, but will re-open new issues and and when other proof regressions emerge...
