### ISSUE TITLE
I some wrong 

### ISSUE THREAD

**Issue by sumatoreo** [rod-chapman/SPARKNaCl#17]
cd test
make

`gprclean -r -Ptestall
"/home/mihail/Projects/sumatoreo/vaniton/third-party/sparknacl/tests/testall.adb.stdout" has been deleted
"/home/mihail/Projects/sumatoreo/vaniton/third-party/sparknacl/tests/testall.adb.stderr" has been deleted
rm -f fntr
rm -f ftestall
gprbuild -Ptestall -XSPARKNACL_RUNTIME_CHECKS=disabled -XSPARKNACL_CONTRACTS=disabled -XSPARKNACL_BUILD_MODE=O3
Compile
   [Ada]          testall.adb
sparknacl-sign.ads:44:11: "Relaxed_Initialization" is not a valid aspect identifier
sparknacl-sign.ads:50:22: unrecognized attribute "Initialized"
gprbuild: *** compilation phase failed
make: *** [Makefile:21: ftestall] Error 4`

**Comment by yannickmoy** [comment]
You are using a too old version of GNAT which does not recognize `Relaxed_Initialization` aspect. You need to use a more recent version.

**Comment by rod-chapman** [comment]
You need GNAT Community 2021, GNAT FSF 11.2.1 or better, or a recent build of GNAT Pro.

**Comment by sumatoreo** [comment]
@yannickmoy @rod-chapman Thanks! Now everything works!
