### ISSUE TITLE
Any interest in adding ChaCha20 stream functionality?

### ISSUE THREAD

**Issue by docandrew** [rod-chapman/SPARKNaCl#18]
TLS 1.3 supports a limited number of cipher suites - one of which is CHACHA20_POLY1305_SHA256. Given that SPARKNaCl already has support for 25519 ecc operations, POLY1305, and SHA256, it seems like the addition of ChaCha20 support would make it possible to use SPARKNaCl as a drop-in crypto solution for a verified SPARK TLS library (with limited cipher and signature support, of course - RSA certificates probably being the limiting factor to widespread adoption, though I expect those to get phased out in favor of ECC certs in the not-too-distant future). Additionally, SSH supports it as one of its cipher suites, as well as some other protocols.

This would make SPARKNaCl no longer strictly a port of the Tweet NaCl code, but there is some precedent - libsodium has added ChaCha20 support making it possible to be used in TLS libraries. From what I understand, ChaCha20 is similar to Salsa20 but I don't know that the primitive operations you've worked hard to write/prove/optimize would be easily transferrable to a ChaCha20 implementation or not. Do you think this is something worth consideration?

**Comment by rod-chapman** [comment]
Thanks for raising this. I believe ChaCha20 is a close relative of Salsa20, so it shouldn't be too hard. It's just a matter of finding the time and effort in between my other work commitments.

**Comment by rod-chapman** [comment]
Are you specifically referring to the variant specified in RFC 8439?

**Comment by docandrew** [comment]
Yes, that's the one, other libraries have something like a "chacha20_ietf" variant - which is a wrapper around the normal algorithm but with the RFC 8439-specified nonce and counter length arguments and a little bit of type-conversion/tweaking to feed them into the regular ChaCha20 function.

If you're open to accepting PRs I can have a go at translating the reference algorithm - I was thinking SPARKNaCl.Stream could have four more public procedures - ChaCha20 and ChaCha20_IETF and then ChaCha20_Xor and ChaCha20_IETF_Xor to match the existing interface. SPARKNaCl.Secretbox could have overloads of Create and Open but using a Stream.ChaCha20_Nonce and then Stream.ChaCha20_IETF_Nonce type - I think these can use the existing MAC package to provide the full AEAD_ChaCha20_Poly1305 cipher suite defined in RFC 8439.

**Comment by rod-chapman** [comment]
OK... some of the heavy lifting is done in SPARKNaCl.Core as well.

I assume you're familiar with SPARK and GNATProve and you have the Community 2021 edition of the toolset?

I guess the tests in SPARKNaCl/tests/secretbox*.adb could be extended to cover whatever KATs are in the RFC too?

**Comment by rod-chapman** [comment]
PS.. what time zone are you in?

**Comment by docandrew** [comment]
I'm all set up with Community 2021 - I've used SPARK a fair amount (not an expert by any means). I see the .gpr has the gnatprove params already set up so that makes life a bit easier! I'm in US/Mountain time zone.

**Comment by rod-chapman** [comment]
Hang on .... I thought that NaCl implemented SHA512 at the moment, not SHA256...

**Comment by rod-chapman** [comment]
That's right... by TweetNaCl only implements SHA-512 so SPARKNaCl does the same at present.

**Comment by docandrew** [comment]
Would it just be a matter of adding a second Digest type of length 256 and adding appropriate overloads?

**Comment by rod-chapman** [comment]
That sounds plausible. I'd change "Digest" to "Digest_512", then add type Digest_256 and the overloaded subprograms...

**Comment by docandrew** [comment]
https://github.com/rod-chapman/SPARKNaCl/pull/19 - just the ChaCha20 and IETF variant stream cipher for now, still need to take a look at SHA-256 and then the full AEAD implementation.
