### ISSUE TITLE
Why Counter parameter in SecretBox.Create

### ISSUE THREAD

**Issue by rod-chapman** [rod-chapman/SPARKNaCl#25]
In the new implementation of SecretBox.Create for ChaCha20-Poly1305-AEAD, why is there a need for "Counter" to be a formal parameter, when the RFC 8439 says the value is always "1". Is there another use case where the caller needs to select a different Counter value?

**Comment by docandrew** [comment]
I added it back as kind of a “just in case”situation. Does it make sense to use a default value of 1 but leave the parameter available?

**Comment by rod-chapman** [comment]
Not sure... I am always wary to step away from what the RFC says unless absolutely sure. In this case, I don't know... so I would remove it unless someone comes along with a justified use-case for it to be there.  If you're OK with that, then I can make the changes here on master.

I have also sent an invite on GitHub to make you a collaborator on the main repo.

**Comment by docandrew** [comment]
It’s easy enough to add it back in later, so I’d say remove it then. Thank you for the invite! I’m happy to accept.

**Comment by rod-chapman** [comment]
The invitation should be in GitHub somewhere... it shows as "pending" at my end...

**Comment by rod-chapman** [comment]
OK... done and pushed onto master.

**Comment by rod-chapman** [comment]
Do you have plans for more updates? I need to get my new_mul branch merged soon to stop it rotting. The performance results are interesting... noticeable improvement at -O1, -O2 and -O3, but horribly slower at -O0 ... hmmm...
