### ISSUE TITLE
Provide incrimental interface

### ISSUE THREAD

**Issue by ethindp** [rod-chapman/SPARKNaCl#26]
So, perhaps I'm missing something or the spec is confusing, but there doesn't appear to be an incremental interface to hash data -- I have to have all the data beforehand. I can't, for example, download a file and, as the file downloads, stream the downloaded information into a hasher to continuously update it before finalizing it. This is something that libsodium has, and its not something that many other Ada crypto libs have (other than the Ada Crypto Library, but that libraries security is questionable, or so the README would have me believe), and it would be nice to have incremental/streaming interfaces for hashing, MACs, encryption/decryption, etc. for those (probably rare but necessary) cases. But maybe I'm missing something really obvious...

**Comment by docandrew** [comment]
You're not missing anything, there's no incremental update-style interfaces for the hash functions. The short answer for why this is so is because the original NaCl/TweetNaCl implementation doesn't have them. There's a little more discussion here: https://github.com/rod-chapman/SPARKNaCl/pull/21#discussion_r855257626 and the referenced link here: https://groups.google.com/g/boring-crypto/c/BpUmNMXKMYQ. For most uses this is OK, but like you said, trying to verify large files without such an interface can be painful.

**Comment by ethindp** [comment]
@docandrew Fair, but I do need that kind of interface. I get the appeal of one-shot interfaces -- its easier to prove, I suppose, and easier to use -- but I'm trying to implement an authentication mechanism where continuous hashing update interfaces are required (primarily because I don't know how to "emulate" it). I suppose I could just go for libsodium-ada, but I was really hoping to use SPARK-verified libraries for crypto in particular. I could go with the Ada-Crypto-Library project, but as I noted above its correctness is questionable. I could just reimplement SHA-2 but that seems a bit extreme.

**Comment by ethindp** [comment]
@docandrew Its an already specified auth mechanism. I'd implement an update mechanism myself but I'm not skilled in crypto and I really don't want to break the integrity of the hash function by accident.

**Comment by rod-chapman** [comment]
I have implemented it several times before. You need a private type that encapsulates the state of the hash function between calls. The state includes a one-block buffer where data gets accumulated before being hashed. The "Finalisation" function then takes care of padding the final block before hashing it. It's not too hard, but you have to be very careful of all the edge cases.

See the declaration of type Context in GNAT.Secure_Hashes.H in the GNAT runtime sources for example.

I am super-busy this week with real work, but will add this to my list of things to look at...

**Comment by ethindp** [comment]
It doesn't appear that this is necessary. GNAT provides implementations of the SHA-1, SHA-2, and MD5 secure hash functions in GNAT.SHA* and GNAT.MD5, so I can just use those. Though I'd prefer to use a formally verified interface, I can settle for the built-in gNAT one.
