### ISSUE TITLE
Alire Crate is missing HMAC API

### ISSUE THREAD

**Issue by kevlar700** [rod-chapman/SPARKNaCl#30]
@docandrew added a HMAC API to the repo. 

https://github.com/rod-chapman/SPARKNaCl/blob/master/src/sparknacl-mac.ads

What would be involved in updating the Alire crate. I would be happy to help?

**Comment by rod-chapman** [comment]
Apologies for that... I have not updated the Alire crate for rather a long time. I have probably forgotten how to do it... I am also in the middle of re-working and simplifying some of the code to improve proof, particularly with CVC5.  How urgently do you need to do this?

**Comment by kevlar700** [comment]
Not urgently. Take your time. It will be used as a fallback to hw accelerated sha256 unless close enough in performance that I can replace it.

**Comment by docandrew** [comment]
Working on a PR to alire-project/alire-index.

**Comment by docandrew** [comment]
https://github.com/alire-project/alire-index/pull/901

**Comment by docandrew** [comment]
@kevlar700 SparkNaCl 4 is now part of the alire-index!

**Comment by kevlar700** [comment]
Fantastic
