### ISSUE TITLE
use of "native" runtime breaks project on windows

### ISSUE THREAD

**Issue by kanigsson** [rod-chapman/SPARKNaCl#6]
On windows, the project can be neither compiled nor proved, because of the
```
   for Runtime ("Ada") use "native";
```

in the project file. I suggest to remove it, it has no purpose (is the default) on linux and is troublesome on windows.

**Comment by rod-chapman** [comment]
That's odd... on Windows using Community 2019, it seems to work fine.
e.g.
 cd tests
 gprbuild -Ptestall

is all OK. What release are you using?

**Comment by rod-chapman** [comment]
OK... fixed in master... seems to make no difference in MacOS or Windows.

**Comment by kanigsson** [comment]
I was also using Community 2019, but I was using `sparknacl.gpr`, maybe it makes a difference ... thanks for fixing anyway.
